# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"temp_dir_creation": "00_utils.ipynb",
         "keep_tmp_file": "00_utils.ipynb",
         "bam2bed": "00_utils.ipynb",
         "cmd_execution": "00_utils.ipynb",
         "loc_distance": "00_utils.ipynb",
         "Vividict": "00_utils.ipynb",
         "gtf_line_split": "01_reference_processing.ipynb",
         "gtf2splicing": "01_reference_processing.ipynb",
         "RefAnnotationExtraction": "01_reference_processing.ipynb",
         "RefProcessWrapper": "01_reference_processing.ipynb",
         "short_reads_sj_import": "01_reference_processing.ipynb",
         "cage_tss_import": "01_reference_processing.ipynb",
         "split_bed_line": "02_preprocessing.ipynb",
         "bed_block_to_splicing": "02_preprocessing.ipynb",
         "read_grouping": "02_preprocessing.ipynb",
         "polya_signal_import": "02_preprocessing.ipynb",
         "PolyAFinder": "02_preprocessing.ipynb",
         "RawAttributeCollection": "03_collapsing.ipynb",
         "ReadCorrectionColappse": "03_collapsing.ipynb",
         "CoCoWrapper": "03_collapsing.ipynb",
         "splicing_to_bed_block": "03_collapsing.ipynb",
         "AlternativeTerminalFinder": "04_RTS_identification.ipynb",
         "TailFinderWrapper": "04_RTS_identification.ipynb",
         "AttributeCollection": "05_refine.ipynb",
         "SingleExonReadRefine": "05_refine.ipynb",
         "MultiExonReadRefine": "05_refine.ipynb",
         "RefineWrapper": "05_refine.ipynb",
         "OutputAssembly": "06_output.ipynb",
         "idx_rearrange": "06_output.ipynb",
         "assembly_output": "06_output.ipynb",
         "LafiteWrapper": "10_wrapper.ipynb",
         "main": "10_wrapper.ipynb"}

modules = ["utils.py",
           "reference_processing.py",
           "preprocessing.py",
           "read_collapsing.py",
           "tailFinder.py",
           "refine.py",
           "output.py",
           "lafite_wrapper.py"]

doc_url = "https://zjzace.github.io/LAFITE/"

git_url = "https://github.com/TF-Chan-Lab/LAFITE/tree/master/"

def custom_doc_links(name): return None
